version: 2
updates:
  # Mantener actualizadas las dependencias de npm (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Mantener actualizadas las acciones de GitHub Actions (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"